development:
  hostname: dbh10.mongolab.com
  port: 27107/
  database: dealtadka_live
  authenticate: true
  username: dealtadka
  password: bpscqd38

development2:
  hostname: localhost
  port: 27107
  database: dealtadka_live
  authenticate: false
  username: 
  password: 
